version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres-container
        environment:
            POSTGRES_DB: spacex
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
    postgres_data:
